ALTER TABLE "Coop" ADD COLUMN "isPublic" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Coop" ADD COLUMN "website" TEXT;
ALTER TABLE "Coop" ADD COLUMN "contactEmail" TEXT;
ALTER TABLE "Coop" ADD COLUMN "phone" TEXT;
